version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
     image: selenium/node-chrome:3.14
     shm_size: '1gb'
     depends_on:
       - hub
     environment:
       - HUB_HOST=hub
  firefox:
     image: selenium/node-firefox:3.14
     shm_size: '1gb'
     depends_on:
       - hub
     environment:
       - HUB_HOST=hub
  search-module1:
     image: poornanandatangirala0811/selenium-docker
     depends_on:
       - chrome
       - firefox
     environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=searchmodule.xml
     volumes:
      - ./output/search-result1:/usr/share/udemy/test-output
  search-module2:
    image: poornanandatangirala0811/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=searchmodule.xml
    volumes:
      - ./output/search-result2:/usr/share/udemy/test-output
  book-flight-module1:
    image: poornanandatangirala0811/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=Book-flight-module.xml
    volumes:
      - ./output/book-flight-result1:/usr/share/udemy/test-output
  book-flight-module2:
    image: poornanandatangirala0811/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=Book-flight-module.xml
    volumes:
      - ./output/book-flight-result2:/usr/share/udemy/test-output